apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    log: "true"
spec:
  containers:
    - name: alpine
      image: alpine
      resources:
            requests:
              cpu: "10m"
              memory: "5M"
            limits:
              cpu: "1000m"
              memory: "128M"
      command: [ "/bin/ash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: logfiles
          mountPath: /var/lib/docker/containers

  volumes:
    - name: logfiles
      hostPath:
        path: /var/lib/docker/containers
        type: Directory
