apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:10.0.1
          securityContext:
            runAsUser: 0
          env:
            - name: KEYCLOAK_FRONTEND_URL
              value: https://keycloak.mlesniak.dev/auth/
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-password
                  key: password
          volumeMounts:
            - name: data
              mountPath: /opt/jboss/keycloak/standalone/data
          resources:
            requests:
              cpu: "100m"
              memory: "256M"
            limits:
              cpu: "1000m"
              memory: "512M"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-pvc


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
