apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-password
                  key: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
          volumeMounts:
            - mountPath: /data
              name: pvc
          resources:
            requests:
              cpu: "100m"
              memory: "10M"
            limits:
              cpu: "1000m"
              memory: "128M"
      volumes:
        - name: pvc
          persistentVolumeClaim:
              claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-external-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

