version: "3.3"
services:
    main:
        labels:
            'log': 'true'
        image: mlesniak/go-demo:latest
        ports:
            - 8080:8080
        volumes:
            - type: volume
              source: logs
              target: /app/logs

    filebeat:
        image: mlesniak/filebeat
        user: root
        environment:
            - SEMATEXT_TOKEN=${SEMATEXT_TOKEN}
        volumes:
            # Access stdout containers
            - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
            - /var/run/docker.sock:/var/run/docker.sock

            # Persist filebeat data to prevent data duplication
            - filebeat-data:/usr/share/filebeat/data/

volumes:
    logs:
    filebeat-data:

