version: "3.3"
services:
    main:
        image: mlesniak/go-demo:latest
        ports:
            - 8080:8080
        volumes:
            - type: volume
              source: logs
              target: /app/logs

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.6.2
        # We should build  a docker container here.
        volumes:
            - type: bind
              source: ./deployments/filebeat/filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
            - type: volume
              source: logs
              target: /logs
            # Persist filebeat data to prevent data duplication
            - filebeat-data:/usr/share/filebeat/data/

volumes:
    logs:
    filebeat-data:


# -----------------------------------------------------------------------------------------------------
# -v $(pwd)/deployments/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml \
# -v $(pwd)/logs:/logs \