version: "3.3"
services:
    # main:
    #     labels:
    #         'log': 'true'
    #     image: mlesniak/go-demo:latest
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - type: volume
    #           source: logs
    #           target: /app/logs

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin


#     filebeat:
#         image: mlesniak/filebeat
#         user: root
#         environment:
#             - SEMATEXT_TOKEN=${SEMATEXT_TOKEN}
#         volumes:
#             # Access stdout containers
#             - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
#             - /var/run/docker.sock:/var/run/docker.sock

#             # Persist filebeat data to prevent data duplication
#             - filebeat-data:/usr/share/filebeat/data/

# volumes:
#     logs:
#     filebeat-data:

