# Main configuration file for our DigitalOcean (mamaged) kubernetes cluster.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
        labels:
          app: demo
    spec:
      containers:
      - name: go-demo
        image: docker.io/mlesniak/go-demo
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "10M"
          limits:
            cpu: "1000m"
            memory: "128M"

